### PR TITLE
Fortran, React and Sql support

### LINKED ISSUE #33: Missing icons
I've seen many filetypes that just show an `?` icon or an incorrect icon. Here I list all I've seen missing:

| Filetype | Current | Expected | Extensions |
| -- | -- | -- | -- |
| Sql | None | Sql | `.sql` |
| Plsql | None | Plsql | `.plsql` |
| JavascriptReact | Javascript | JavascriptReact | `.jsx` |
| TypescriptReact | Typescript | TypescriptReact | `.tsx` |
| Brainfuck | None | Brainfuck | `.bf` |
| C Header | C++ | C | `.h` |
| Fortran | None | Fortran | `.f`, `.for`, `.f90`, `.f95`, `.f03` |

### PR DESCRIPTION
**Pull request by eruizc-dev**
I gave up on C header files (since vim thinks they're cpp I'd say it should be fixed there) and brainfuck (becauise it has no logo...)

### Icons!

React (both for jsx and tsx):
 - https://cdn.idevie.com/wp-content/uploads/2015/12/React.js_logo.svg_.png

Fortran (so many file extensions...):
 - https://fortran-lang.org/assets/img/fortran_logo_256x256.png

SQL! I'll let you decide:
 - https://blog.composable.ai/wp-content/uploads/2017/02/sql-logo.png
 - https://w7.pngwing.com/pngs/28/601/png-transparent-sql-logo-illustration-microsoft-azure-sql-database-microsoft-sql-server-database-blue-text-logo.png

PL/SQL, for Oracle databases:
 - Use the same as sql
 - Use the same as sql but red
 - http://www.tutego.de/images/seminare/logos/oracle.png
 - https://pic.cr173.com/up/2016-1/201611412346.png

Closes #33

### CODE REVIEW

**Comment by hugolgst** [comment]
Fortan logo is too small (less than 512x512). Could you provide a new one?

**Comment by eruizc-dev** [comment]
@hugolgst sure! Here it is:

https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Fortran_logo.svg/1200px-Fortran_logo.svg.png

**Review by hugolgst — APPROVED** [review]
LGTM

**Comment by hugolgst** [comment]
Sorry for the delay

**Pull request merged**
